### ISSUE TITLE
Can't build the project with the 'dagger-browser-processor'

### ISSUE THREAD

**Issue by ErikMedina** [Snapchat/dagger-browser#5]
Hi,

I'm trying to setup dagger-browser into my project which is using **dagger-android** but I'm facing issues during the building of my project. I have done the following steps:
- Clone `dagger-browser` project
- Add to the `settings.gradle` of my project:
```
include ':dagger-browser-processor'
project(':dagger-browser-processor').projectDir = new File(rootDir, "../dagger-browser/plugin/lib")
```
- Add the `dagger-browser` dependency into the `build.gradle` of the `app` module:
```
annotationProcessor project(':dagger-browser-processor')
```

And I get the following error:
```
Unable to find a matching configuration of project :dagger-browser-processor:
  - None of the consumable configurations have attributes.
```

Any thoughts?

**Comment by bjdodson** [comment]
Is the path from your project go dagger-browser correct in your settings file?

We're working to get the plugin published to simplify this step, hoping to have it in the next few days.

**Comment by ErikMedina** [comment]
@bjdodson I managed to make it work in another project using the same configuration I mentioned. One difference that could be the problem is that the working project is using `dagger` and the failing project is using `dagger-android`.
